name: Terraform-Infra-Robot  # Changed the name so it stands out

on:
  push:
    branches: [ main ]

jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
