# 1. Create the Internet Gateway (The physical 'door' to the internet)
resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.devops_vpc.id

  tags = {
    Name = "manikanta-igw"
  }
}

# 2. Create a Route Table (The 'rules' for where traffic goes)
resource "aws_route_table" "public_rt" {
  vpc_id = aws_vpc.devops_vpc.id

  route {
    cidr_block = "0.0.0.0/0" # This means 'all traffic'
    gateway_id = aws_internet_gateway.igw.id
  }

  tags = {
    Name = "manikanta-public-rt"
  }
}
